# Generated by Django 3.0.2 on 2020-05-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OredrItem',
            new_name='OrderItem',
        ),
    ]
